### ISSUE TITLE
初中理化的教材建议

### ISSUE THREAD

**Issue by wlbksy** [weiyayun925104/Mathematics_Physics_Chemistry_Books#2]
看到 readme 中有初高中的数学教材建议，也有高中的物理化学教材建议。麻烦添加一下初中的物理、化学教材的建议

**Comment by weiyayun925104** [comment]
我已经收到，谢谢。

**Comment by weiyayun925104** [comment]
我在知乎的文章 如何学习中学数学 物理 化学 生物 语文 英语 里面有介绍初中物理 化学的教材 

https://zhuanlan.zhihu.com/p/648742148

我把其中的内容截取出来
初中物理

主要学习 初中物理 第一册 2001 人教版 初中物理 第二册 2001 人教版

对比学习 初中物理 第一册 1993 人教版 初中物理 第二册 1993 人教版

对比学习 初中物理 第一册 八十年代 人教版 初中物理 第二册 八十年代 人教版

1套自学中学物理非常好的丛书

数理化自学丛书第2版 物理 第1册 到 第4册

初中化学

主要学习 初中化学 2001 人教版

对比学习 初中化学 1995 人教版

对比学习 初中化学 八十年代 人教版

1套自学中学化学非常好的丛书

数理化自学丛书第2版 化学 第1册 到 第4册

**Comment by wlbksy** [comment]
非常谢谢。我再翻翻您的文章。也麻烦您更到 readme 里面。
